
title: "Passivo e Riflessivo"
description: "Un sito creato con Jekyll e tema So Simple"
baseurl: ""
url: ""

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Tema locale
theme: null

include:
  - so-simple-theme

exclude:
  - README.md
