title: Pigro e Passivo
description: Un blog pigro, passivo e consapevole
baseurl: ""
url: "https://TUO_USERNAME.github.io"

remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

theme_skin: "default"
lang: "it"

author:
  name: Pigro e Passivo
  avatar: /assets/avatar.png
