title: "Pigro e Passivo"
description: "Il mio nuovo sito"
url: "https://claudiostoduto.github.io"
baseurl: "/Pigroepassivo"

# Configurazione Tema
locale: "it-IT"
# Usiamo il remote_theme per forzare GitHub a caricare i file corretti se i locali sono corrotti
remote_theme: "mmistakes/so-simple-theme"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Impostazioni per i link

permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# Menu di navigazione
navigation:
  - title: "Home"
    url: /
  - title: "Chi sono"
    url: /chi-sono/
  - title: "Blog"
    url: /posts/
  - title: "Tag"
    url: /tags/