title: "Pigro e Passivo"
description: "Un blog molto, molto lento"
locale: "it-IT"
url: "https://claudiostoduto.github.io"
baseurl: "/Pigroepassivo"            

# Forza GitHub a ignorare i temi predefiniti
remote_theme: mmistakes/so-simple-theme

# Plugin necessari
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Percorso dei CSS del tema So Simple
skin: "/assets/css/skins/default.css"

navigation:
  - title: "Home"
    url: /
  - title: "Chi sono"
    url: /chi-sono/
  - title: "Blog"
    url: /posts/
  - title: "Tag"
    url: /tags/

    # Forza i layout corretti
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page