title: "Nomarin"
description: "Un blog molto, molto lento"
url: "https://claudiostoduto.github.io"
baseurl: "/Pigroepassivo"

# Configurazione Tema
locale: "it-IT"
# Usiamo il remote_theme per forzare GitHub a caricare i file corretti se i locali sono corrotti
remote_theme: "mmistakes/so-simple-theme"

search_full_content: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

logo: "/assets/images/logo.png" # path of site logo, e.g. "/assets/images/logo.png"

google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: mmistakes # site's Twitter username

# Impostazioni per i link

permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# Site Author
author:
  name: Mr. Claus
  picture: /images/michael-rose-photo.jpg
  email:
  twitter: mmistakes
  links:
    - title: Twitter
      url: https://twitter.com/mmistakes
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/mmistakes
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/mmistakes
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/mrclaus_xyz
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/mrclaus_xyz
    icon: fab fa-instagram
  - title: Feed
    url: feed
    icon: fas fa-rss-square