title: "Passivo e Riflessivo"
description: "Il mio nuovo sito"
locale: "it-IT"

# Forza GitHub a ignorare i temi predefiniti
theme: null
remote_theme: null

# Plugin necessari
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Percorso dei CSS del tema So Simple
skin: "/assets/css/skins/default.css"