title: "Passivo e Riflessivo"
locale: "it-IT"

# Plugin necessari per So Simple
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Impostazioni di paginazione
paginate: 10
paginate_path: /page:num/

# Forza Jekyll a non cercare temi esterni
theme: null