title: "Pigro e Passivo"
description: "Il mio nuovo sito"
locale: "it-IT"

# Forza GitHub a usare i file nelle tue cartelle _layouts e _includes
theme: null
remote_theme: null

# Configurazione del tema So Simple
skin: "/assets/css/skins/default.css"

navigation:
  - title: "Chi sono"
    url: /chi-sono/
  - title: "Archivio"
    url: /posts/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

paginate: 10
paginate_path: /page:num/