title: Pigro e Passivo
description: Un blog pigro, passivo e consapevole
url: "https://www.pigroepassivo.it"
baseurl: ""

theme: null
lang: it
theme_skin: default

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache